/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

/** Movable demand profile value */
@org.apache.avro.specific.AvroGenerated
public class TaskMovableDemandValueDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 2773113430174034432L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TaskMovableDemandValueDto\",\"namespace\":\"com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task\",\"doc\":\"Movable demand profile value\",\"fields\":[{\"name\":\"order\",\"type\":\"long\",\"doc\":\"Profile value ordering number\"},{\"name\":\"durationMinutes\",\"type\":\"long\",\"doc\":\"Profile value duration in minutes\"},{\"name\":\"value\",\"type\":\"double\",\"doc\":\"Demand value of profile\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TaskMovableDemandValueDto> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TaskMovableDemandValueDto> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TaskMovableDemandValueDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TaskMovableDemandValueDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TaskMovableDemandValueDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TaskMovableDemandValueDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TaskMovableDemandValueDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TaskMovableDemandValueDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TaskMovableDemandValueDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Profile value ordering number */
  private long order;
  /** Profile value duration in minutes */
  private long durationMinutes;
  /** Demand value of profile */
  private double value;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TaskMovableDemandValueDto() {}

  /**
   * All-args constructor.
   * @param order Profile value ordering number
   * @param durationMinutes Profile value duration in minutes
   * @param value Demand value of profile
   */
  public TaskMovableDemandValueDto(java.lang.Long order, java.lang.Long durationMinutes, java.lang.Double value) {
    this.order = order;
    this.durationMinutes = durationMinutes;
    this.value = value;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return order;
    case 1: return durationMinutes;
    case 2: return value;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: order = (java.lang.Long)value$; break;
    case 1: durationMinutes = (java.lang.Long)value$; break;
    case 2: value = (java.lang.Double)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'order' field.
   * @return Profile value ordering number
   */
  public long getOrder() {
    return order;
  }


  /**
   * Sets the value of the 'order' field.
   * Profile value ordering number
   * @param value the value to set.
   */
  public void setOrder(long value) {
    this.order = value;
  }

  /**
   * Gets the value of the 'durationMinutes' field.
   * @return Profile value duration in minutes
   */
  public long getDurationMinutes() {
    return durationMinutes;
  }


  /**
   * Sets the value of the 'durationMinutes' field.
   * Profile value duration in minutes
   * @param value the value to set.
   */
  public void setDurationMinutes(long value) {
    this.durationMinutes = value;
  }

  /**
   * Gets the value of the 'value' field.
   * @return Demand value of profile
   */
  public double getValue() {
    return value;
  }


  /**
   * Sets the value of the 'value' field.
   * Demand value of profile
   * @param value the value to set.
   */
  public void setValue(double value) {
    this.value = value;
  }

  /**
   * Creates a new TaskMovableDemandValueDto RecordBuilder.
   * @return A new TaskMovableDemandValueDto RecordBuilder
   */
  public static com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder newBuilder() {
    return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder();
  }

  /**
   * Creates a new TaskMovableDemandValueDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TaskMovableDemandValueDto RecordBuilder
   */
  public static com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder newBuilder(com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder other) {
    if (other == null) {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder();
    } else {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder(other);
    }
  }

  /**
   * Creates a new TaskMovableDemandValueDto RecordBuilder by copying an existing TaskMovableDemandValueDto instance.
   * @param other The existing instance to copy.
   * @return A new TaskMovableDemandValueDto RecordBuilder
   */
  public static com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder newBuilder(com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto other) {
    if (other == null) {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder();
    } else {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for TaskMovableDemandValueDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TaskMovableDemandValueDto>
    implements org.apache.avro.data.RecordBuilder<TaskMovableDemandValueDto> {

    /** Profile value ordering number */
    private long order;
    /** Profile value duration in minutes */
    private long durationMinutes;
    /** Demand value of profile */
    private double value;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.order)) {
        this.order = data().deepCopy(fields()[0].schema(), other.order);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.durationMinutes)) {
        this.durationMinutes = data().deepCopy(fields()[1].schema(), other.durationMinutes);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing TaskMovableDemandValueDto instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.order)) {
        this.order = data().deepCopy(fields()[0].schema(), other.order);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.durationMinutes)) {
        this.durationMinutes = data().deepCopy(fields()[1].schema(), other.durationMinutes);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.value)) {
        this.value = data().deepCopy(fields()[2].schema(), other.value);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'order' field.
      * Profile value ordering number
      * @return The value.
      */
    public long getOrder() {
      return order;
    }


    /**
      * Sets the value of the 'order' field.
      * Profile value ordering number
      * @param value The value of 'order'.
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder setOrder(long value) {
      validate(fields()[0], value);
      this.order = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'order' field has been set.
      * Profile value ordering number
      * @return True if the 'order' field has been set, false otherwise.
      */
    public boolean hasOrder() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'order' field.
      * Profile value ordering number
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder clearOrder() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'durationMinutes' field.
      * Profile value duration in minutes
      * @return The value.
      */
    public long getDurationMinutes() {
      return durationMinutes;
    }


    /**
      * Sets the value of the 'durationMinutes' field.
      * Profile value duration in minutes
      * @param value The value of 'durationMinutes'.
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder setDurationMinutes(long value) {
      validate(fields()[1], value);
      this.durationMinutes = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'durationMinutes' field has been set.
      * Profile value duration in minutes
      * @return True if the 'durationMinutes' field has been set, false otherwise.
      */
    public boolean hasDurationMinutes() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'durationMinutes' field.
      * Profile value duration in minutes
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder clearDurationMinutes() {
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'value' field.
      * Demand value of profile
      * @return The value.
      */
    public double getValue() {
      return value;
    }


    /**
      * Sets the value of the 'value' field.
      * Demand value of profile
      * @param value The value of 'value'.
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder setValue(double value) {
      validate(fields()[2], value);
      this.value = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'value' field has been set.
      * Demand value of profile
      * @return True if the 'value' field has been set, false otherwise.
      */
    public boolean hasValue() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'value' field.
      * Demand value of profile
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskMovableDemandValueDto.Builder clearValue() {
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TaskMovableDemandValueDto build() {
      try {
        TaskMovableDemandValueDto record = new TaskMovableDemandValueDto();
        record.order = fieldSetFlags()[0] ? this.order : (java.lang.Long) defaultValue(fields()[0]);
        record.durationMinutes = fieldSetFlags()[1] ? this.durationMinutes : (java.lang.Long) defaultValue(fields()[1]);
        record.value = fieldSetFlags()[2] ? this.value : (java.lang.Double) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TaskMovableDemandValueDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<TaskMovableDemandValueDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TaskMovableDemandValueDto>
    READER$ = (org.apache.avro.io.DatumReader<TaskMovableDemandValueDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.order);

    out.writeLong(this.durationMinutes);

    out.writeDouble(this.value);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.order = in.readLong();

      this.durationMinutes = in.readLong();

      this.value = in.readDouble();

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.order = in.readLong();
          break;

        case 1:
          this.durationMinutes = in.readLong();
          break;

        case 2:
          this.value = in.readDouble();
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










