/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TaskValidationMessagesDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3580642996356493183L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TaskValidationMessagesDto\",\"namespace\":\"com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation\",\"fields\":[{\"name\":\"taskId\",\"type\":\"long\",\"doc\":\"Task identifier\"},{\"name\":\"validationSummary\",\"type\":\"string\",\"doc\":\"Short summary of validation\",\"default\":\"\"},{\"name\":\"messages\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"TaskValidationMessageDto\",\"fields\":[{\"name\":\"level\",\"type\":{\"type\":\"enum\",\"name\":\"TaskValidationMessageLevelDto\",\"symbols\":[\"DEBUG\",\"INFO\",\"WARN\",\"ERROR\"]},\"doc\":\"Message level. Error messages will result in calculation process abort\"},{\"name\":\"objectType\",\"type\":{\"type\":\"enum\",\"name\":\"ObjectTypeDto\",\"symbols\":[\"CONTRACT\",\"DEMAND\",\"TARIFF\",\"PRODUCTION\",\"STORAGE\",\"MOVABLE_DEMAND\"]},\"doc\":\"Type of object that message concerns\"},{\"name\":\"baseObjectName\",\"type\":\"string\",\"doc\":\"Base object name\"},{\"name\":\"id\",\"type\":\"long\",\"doc\":\"Base object ID\"},{\"name\":\"revisionId\",\"type\":\"long\",\"doc\":\"Revision ID\"},{\"name\":\"message\",\"type\":\"string\",\"doc\":\"Validation message explanation\"}]}},\"doc\":\"List of validation messages\",\"default\":[]}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TaskValidationMessagesDto> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TaskValidationMessagesDto> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TaskValidationMessagesDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TaskValidationMessagesDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TaskValidationMessagesDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TaskValidationMessagesDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TaskValidationMessagesDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TaskValidationMessagesDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TaskValidationMessagesDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Task identifier */
  private long taskId;
  /** Short summary of validation */
  private java.lang.CharSequence validationSummary;
  /** List of validation messages */
  private java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> messages;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TaskValidationMessagesDto() {}

  /**
   * All-args constructor.
   * @param taskId Task identifier
   * @param validationSummary Short summary of validation
   * @param messages List of validation messages
   */
  public TaskValidationMessagesDto(java.lang.Long taskId, java.lang.CharSequence validationSummary, java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> messages) {
    this.taskId = taskId;
    this.validationSummary = validationSummary;
    this.messages = messages;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return taskId;
    case 1: return validationSummary;
    case 2: return messages;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: taskId = (java.lang.Long)value$; break;
    case 1: validationSummary = (java.lang.CharSequence)value$; break;
    case 2: messages = (java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'taskId' field.
   * @return Task identifier
   */
  public long getTaskId() {
    return taskId;
  }


  /**
   * Sets the value of the 'taskId' field.
   * Task identifier
   * @param value the value to set.
   */
  public void setTaskId(long value) {
    this.taskId = value;
  }

  /**
   * Gets the value of the 'validationSummary' field.
   * @return Short summary of validation
   */
  public java.lang.CharSequence getValidationSummary() {
    return validationSummary;
  }


  /**
   * Sets the value of the 'validationSummary' field.
   * Short summary of validation
   * @param value the value to set.
   */
  public void setValidationSummary(java.lang.CharSequence value) {
    this.validationSummary = value;
  }

  /**
   * Gets the value of the 'messages' field.
   * @return List of validation messages
   */
  public java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> getMessages() {
    return messages;
  }


  /**
   * Sets the value of the 'messages' field.
   * List of validation messages
   * @param value the value to set.
   */
  public void setMessages(java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> value) {
    this.messages = value;
  }

  /**
   * Creates a new TaskValidationMessagesDto RecordBuilder.
   * @return A new TaskValidationMessagesDto RecordBuilder
   */
  public static com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder newBuilder() {
    return new com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder();
  }

  /**
   * Creates a new TaskValidationMessagesDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TaskValidationMessagesDto RecordBuilder
   */
  public static com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder newBuilder(com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder other) {
    if (other == null) {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder();
    } else {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder(other);
    }
  }

  /**
   * Creates a new TaskValidationMessagesDto RecordBuilder by copying an existing TaskValidationMessagesDto instance.
   * @param other The existing instance to copy.
   * @return A new TaskValidationMessagesDto RecordBuilder
   */
  public static com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder newBuilder(com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto other) {
    if (other == null) {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder();
    } else {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for TaskValidationMessagesDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TaskValidationMessagesDto>
    implements org.apache.avro.data.RecordBuilder<TaskValidationMessagesDto> {

    /** Task identifier */
    private long taskId;
    /** Short summary of validation */
    private java.lang.CharSequence validationSummary;
    /** List of validation messages */
    private java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> messages;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.taskId)) {
        this.taskId = data().deepCopy(fields()[0].schema(), other.taskId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.validationSummary)) {
        this.validationSummary = data().deepCopy(fields()[1].schema(), other.validationSummary);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.messages)) {
        this.messages = data().deepCopy(fields()[2].schema(), other.messages);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing TaskValidationMessagesDto instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.taskId)) {
        this.taskId = data().deepCopy(fields()[0].schema(), other.taskId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.validationSummary)) {
        this.validationSummary = data().deepCopy(fields()[1].schema(), other.validationSummary);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.messages)) {
        this.messages = data().deepCopy(fields()[2].schema(), other.messages);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'taskId' field.
      * Task identifier
      * @return The value.
      */
    public long getTaskId() {
      return taskId;
    }


    /**
      * Sets the value of the 'taskId' field.
      * Task identifier
      * @param value The value of 'taskId'.
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder setTaskId(long value) {
      validate(fields()[0], value);
      this.taskId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'taskId' field has been set.
      * Task identifier
      * @return True if the 'taskId' field has been set, false otherwise.
      */
    public boolean hasTaskId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'taskId' field.
      * Task identifier
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder clearTaskId() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'validationSummary' field.
      * Short summary of validation
      * @return The value.
      */
    public java.lang.CharSequence getValidationSummary() {
      return validationSummary;
    }


    /**
      * Sets the value of the 'validationSummary' field.
      * Short summary of validation
      * @param value The value of 'validationSummary'.
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder setValidationSummary(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.validationSummary = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'validationSummary' field has been set.
      * Short summary of validation
      * @return True if the 'validationSummary' field has been set, false otherwise.
      */
    public boolean hasValidationSummary() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'validationSummary' field.
      * Short summary of validation
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder clearValidationSummary() {
      validationSummary = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'messages' field.
      * List of validation messages
      * @return The value.
      */
    public java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> getMessages() {
      return messages;
    }


    /**
      * Sets the value of the 'messages' field.
      * List of validation messages
      * @param value The value of 'messages'.
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder setMessages(java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> value) {
      validate(fields()[2], value);
      this.messages = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'messages' field has been set.
      * List of validation messages
      * @return True if the 'messages' field has been set, false otherwise.
      */
    public boolean hasMessages() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'messages' field.
      * List of validation messages
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessagesDto.Builder clearMessages() {
      messages = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TaskValidationMessagesDto build() {
      try {
        TaskValidationMessagesDto record = new TaskValidationMessagesDto();
        record.taskId = fieldSetFlags()[0] ? this.taskId : (java.lang.Long) defaultValue(fields()[0]);
        record.validationSummary = fieldSetFlags()[1] ? this.validationSummary : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.messages = fieldSetFlags()[2] ? this.messages : (java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto>) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TaskValidationMessagesDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<TaskValidationMessagesDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TaskValidationMessagesDto>
    READER$ = (org.apache.avro.io.DatumReader<TaskValidationMessagesDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeLong(this.taskId);

    out.writeString(this.validationSummary);

    long size0 = this.messages.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto e0: this.messages) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.taskId = in.readLong();

      this.validationSummary = in.readString(this.validationSummary instanceof Utf8 ? (Utf8)this.validationSummary : null);

      long size0 = in.readArrayStart();
      java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> a0 = this.messages;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto>((int)size0, SCHEMA$.getField("messages").schema());
        this.messages = a0;
      } else a0.clear();
      SpecificData.Array<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.taskId = in.readLong();
          break;

        case 1:
          this.validationSummary = in.readString(this.validationSummary instanceof Utf8 ? (Utf8)this.validationSummary : null);
          break;

        case 2:
          long size0 = in.readArrayStart();
          java.util.List<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> a0 = this.messages;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto>((int)size0, SCHEMA$.getField("messages").schema());
            this.messages = a0;
          } else a0.clear();
          SpecificData.Array<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.github.kacperpotapczyk.pvoptimizer.avro.calculationpreprocessor.validation.TaskValidationMessageDto();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










