CREATE TABLE movable_demand (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT pk_movable_demand PRIMARY KEY (id)
);
ALTER TABLE movable_demand ADD CONSTRAINT uc_movable_demand_name_is_deleted UNIQUE (name, is_deleted);

CREATE TABLE movable_demand_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    revision_number BIGINT NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    base_id BIGINT,
    CONSTRAINT pk_movable_demand_revision PRIMARY KEY (id)
);
ALTER TABLE movable_demand_revision ADD CONSTRAINT uc_movable_demand_revision_number UNIQUE (base_id, revision_number);
ALTER TABLE movable_demand_revision ADD CONSTRAINT FK_MOVABLE_DEMAND_REVISION_ON_BASE FOREIGN KEY (base_id) REFERENCES movable_demand (id);

CREATE TABLE movable_demand_start (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    revision_id BIGINT NOT NULL,
    start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    CONSTRAINT pk_movable_demand_start PRIMARY KEY (id)
);
ALTER TABLE movable_demand_start ADD CONSTRAINT FK_MOVABLE_DEMAND_START_ON_REVISION FOREIGN KEY (revision_id) REFERENCES movable_demand_revision (id);
CREATE INDEX idx_movable_demand_start_revision_id ON movable_demand_start(revision_id);

CREATE TABLE movable_demand_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    revision_id BIGINT NOT NULL,
    value_order BIGINT NOT NULL,
    duration BIGINT NOT NULL,
    demand DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_movable_demand_value PRIMARY KEY (id)
);
ALTER TABLE movable_demand_value ADD CONSTRAINT FK_MOVABLE_DEMAND_VALUE_ON_REVISION FOREIGN KEY (revision_id) REFERENCES movable_demand_revision (id);
CREATE INDEX idx_movable_demand_value_revision_id ON movable_demand_value(revision_id);