CREATE TABLE movable_demand_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movable_demand_revision_id BIGINT NOT NULL,
    task_result_id BIGINT NOT NULL,
    CONSTRAINT pk_movable_demand_result PRIMARY KEY (id)
);
ALTER TABLE movable_demand_result ADD CONSTRAINT FK_MOVABLE_DEMAND_RESULT_ON_MOVABLE_DEMAND_REVISION FOREIGN KEY (movable_demand_revision_id) REFERENCES movable_demand_revision (id);
ALTER TABLE movable_demand_result ADD CONSTRAINT FK_MOVABLE_DEMAND_RESULT_ON_TASK_RESULT FOREIGN KEY (task_result_id) REFERENCES task_result (id);
CREATE INDEX idx_movable_demand_result_task_result_id ON movable_demand_result(task_result_id);

CREATE TABLE movable_demand_result_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    movable_demand_result_id BIGINT,
    date_time_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    date_time_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    power DOUBLE PRECISION NOT NULL,
    energy DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_movable_demand_result_value PRIMARY KEY (id)
);
ALTER TABLE movable_demand_result_value ADD CONSTRAINT FK_MOVABLE_DEMAND_RESULT_VALUE_ON_MOVABLE_DEMAND_RESULT FOREIGN KEY (movable_demand_result_id) REFERENCES movable_demand_result (id);
CREATE INDEX idx_movable_demand_result_value_movable_demand_result_id ON movable_demand_result_value(movable_demand_result_id);