CREATE TABLE contract (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    contract_type INTEGER NOT NULL,
    tariff_base_id BIGINT,
    CONSTRAINT pk_contract PRIMARY KEY (id)
);
ALTER TABLE contract ADD CONSTRAINT uc_contract_name_is_deleted UNIQUE (name, is_deleted);
ALTER TABLE contract ADD CONSTRAINT FK_CONTRACT_ON_TARIFF_BASE FOREIGN KEY (tariff_base_id) REFERENCES tariff (id);

CREATE TABLE contract_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    revision_number BIGINT NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    base_id BIGINT,
    CONSTRAINT pk_contract_revision PRIMARY KEY (id)
);
ALTER TABLE contract_revision ADD CONSTRAINT uc_contract_revision_number UNIQUE (base_id, revision_number);
ALTER TABLE contract_revision ADD CONSTRAINT FK_CONTRACT_REVISION_ON_BASE FOREIGN KEY (base_id) REFERENCES contract (id);

CREATE TABLE contract_min_power_constraint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    constraint_value DOUBLE PRECISION NOT NULL,
    date_time_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    date_time_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revision_id BIGINT,
    CONSTRAINT pk_contract_min_power_constraint PRIMARY KEY (id)
);
ALTER TABLE contract_min_power_constraint ADD CONSTRAINT FK_CONTRACT_MIN_POWER_CONSTRAINT_ON_REVISION FOREIGN KEY (revision_id) REFERENCES contract_revision (id);
CREATE INDEX idx_contract_min_power_constraint_revision_id ON contract_min_power_constraint(revision_id);

CREATE TABLE contract_max_power_constraint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    constraint_value DOUBLE PRECISION NOT NULL,
    date_time_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    date_time_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revision_id BIGINT,
    CONSTRAINT pk_contract_max_power_constraint PRIMARY KEY (id)
);
ALTER TABLE contract_max_power_constraint ADD CONSTRAINT FK_CONTRACT_MAX_POWER_CONSTRAINT_ON_REVISION FOREIGN KEY (revision_id) REFERENCES contract_revision (id);
CREATE INDEX idx_contract_max_power_constraint_revision_id ON contract_max_power_constraint(revision_id);

CREATE TABLE contract_min_energy_constraint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    constraint_value DOUBLE PRECISION NOT NULL,
    date_time_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    date_time_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revision_id BIGINT,
    CONSTRAINT pk_contract_min_energy_constraint PRIMARY KEY (id)
);
ALTER TABLE contract_min_energy_constraint ADD CONSTRAINT FK_CONTRACT_MIN_ENERGY_CONSTRAINT_ON_REVISION FOREIGN KEY (revision_id) REFERENCES contract_revision (id);
CREATE INDEX idx_contract_min_energy_constraint_revision_id ON contract_min_energy_constraint(revision_id);

CREATE TABLE contract_max_energy_constraint (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    constraint_value DOUBLE PRECISION NOT NULL,
    date_time_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    date_time_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    revision_id BIGINT,
    CONSTRAINT pk_contract_max_energy_constraint PRIMARY KEY (id)
);
ALTER TABLE contract_max_energy_constraint ADD CONSTRAINT FK_CONTRACT_MAX_ENERGY_CONSTRAINT_ON_REVISION FOREIGN KEY (revision_id) REFERENCES contract_revision (id);
CREATE INDEX idx_contract_max_energy_constraint_revision_id ON contract_max_energy_constraint(revision_id);