CREATE TABLE contract_result (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_revision_id BIGINT NOT NULL,
    task_result_id BIGINT NOT NULL,
    CONSTRAINT pk_contract_result PRIMARY KEY (id)
);
ALTER TABLE contract_result ADD CONSTRAINT FK_CONTRACT_RESULT_ON_CONTRACT_REVISION FOREIGN KEY (contract_revision_id) REFERENCES contract_revision (id);
ALTER TABLE contract_result ADD CONSTRAINT FK_CONTRACT_RESULT_ON_TASK_RESULT FOREIGN KEY (task_result_id) REFERENCES task_result (id);
CREATE INDEX idx_contract_result_task_result_id ON contract_result(task_result_id);

CREATE TABLE contract_result_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    contract_result_id BIGINT,
    date_time_start TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    date_time_end TIMESTAMP WITHOUT TIME ZONE NOT NULL,
    power DOUBLE PRECISION NOT NULL,
    energy DOUBLE PRECISION NOT NULL,
    cost DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_contract_result_value PRIMARY KEY (id)
);
ALTER TABLE contract_result_value ADD CONSTRAINT FK_CONTRACT_RESULT_VALUE_ON_CONTRACT_RESULT FOREIGN KEY (contract_result_id) REFERENCES contract_result (id);
CREATE INDEX idx_contract_result_value_contract_result_id ON contract_result_value(contract_result_id);