CREATE TABLE production (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(255) NOT NULL,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    CONSTRAINT pk_production PRIMARY KEY (id)
);
ALTER TABLE production ADD CONSTRAINT uc_production_name_is_deleted UNIQUE (name, is_deleted);


CREATE TABLE production_revision (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    revision_number BIGINT NOT NULL,
    created_date TIMESTAMP WITHOUT TIME ZONE,
    is_deleted BOOLEAN DEFAULT FALSE NOT NULL,
    base_id BIGINT,
    CONSTRAINT pk_production_revision PRIMARY KEY (id)
);
ALTER TABLE production_revision ADD CONSTRAINT uc_production_revision_number UNIQUE (base_id, revision_number);
ALTER TABLE production_revision ADD CONSTRAINT FK_PRODUCTION_REVISION_ON_PRODUCTION_BASE FOREIGN KEY (base_id) REFERENCES production (id);


CREATE TABLE production_value (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    revision_id BIGINT,
    date_time TIMESTAMP  WITHOUT TIME ZONE,
    production DOUBLE PRECISION NOT NULL,
    CONSTRAINT pk_production_value PRIMARY KEY (id)
);
ALTER TABLE production_value ADD CONSTRAINT FK_PRODUCTION_VALUE_ON_REVISION FOREIGN KEY (revision_id) REFERENCES production_revision (id);
CREATE INDEX idx_production_value_revision_id ON production_value(revision_id);