/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class TaskStorageConstraintDto extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 3126018367317264929L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"TaskStorageConstraintDto\",\"namespace\":\"com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task\",\"fields\":[{\"name\":\"constraintValue\",\"type\":\"double\",\"doc\":\"Constraint value\"},{\"name\":\"dateTimeStart\",\"type\":\"string\",\"doc\":\"Date and time of constraint start\"},{\"name\":\"dateTimeEnd\",\"type\":\"string\",\"doc\":\"Date and time of constraint end\"}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<TaskStorageConstraintDto> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<TaskStorageConstraintDto> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<TaskStorageConstraintDto> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<TaskStorageConstraintDto> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<TaskStorageConstraintDto> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this TaskStorageConstraintDto to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a TaskStorageConstraintDto from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a TaskStorageConstraintDto instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static TaskStorageConstraintDto fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  /** Constraint value */
  private double constraintValue;
  /** Date and time of constraint start */
  private java.lang.CharSequence dateTimeStart;
  /** Date and time of constraint end */
  private java.lang.CharSequence dateTimeEnd;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public TaskStorageConstraintDto() {}

  /**
   * All-args constructor.
   * @param constraintValue Constraint value
   * @param dateTimeStart Date and time of constraint start
   * @param dateTimeEnd Date and time of constraint end
   */
  public TaskStorageConstraintDto(java.lang.Double constraintValue, java.lang.CharSequence dateTimeStart, java.lang.CharSequence dateTimeEnd) {
    this.constraintValue = constraintValue;
    this.dateTimeStart = dateTimeStart;
    this.dateTimeEnd = dateTimeEnd;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return constraintValue;
    case 1: return dateTimeStart;
    case 2: return dateTimeEnd;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: constraintValue = (java.lang.Double)value$; break;
    case 1: dateTimeStart = (java.lang.CharSequence)value$; break;
    case 2: dateTimeEnd = (java.lang.CharSequence)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'constraintValue' field.
   * @return Constraint value
   */
  public double getConstraintValue() {
    return constraintValue;
  }


  /**
   * Sets the value of the 'constraintValue' field.
   * Constraint value
   * @param value the value to set.
   */
  public void setConstraintValue(double value) {
    this.constraintValue = value;
  }

  /**
   * Gets the value of the 'dateTimeStart' field.
   * @return Date and time of constraint start
   */
  public java.lang.CharSequence getDateTimeStart() {
    return dateTimeStart;
  }


  /**
   * Sets the value of the 'dateTimeStart' field.
   * Date and time of constraint start
   * @param value the value to set.
   */
  public void setDateTimeStart(java.lang.CharSequence value) {
    this.dateTimeStart = value;
  }

  /**
   * Gets the value of the 'dateTimeEnd' field.
   * @return Date and time of constraint end
   */
  public java.lang.CharSequence getDateTimeEnd() {
    return dateTimeEnd;
  }


  /**
   * Sets the value of the 'dateTimeEnd' field.
   * Date and time of constraint end
   * @param value the value to set.
   */
  public void setDateTimeEnd(java.lang.CharSequence value) {
    this.dateTimeEnd = value;
  }

  /**
   * Creates a new TaskStorageConstraintDto RecordBuilder.
   * @return A new TaskStorageConstraintDto RecordBuilder
   */
  public static com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder newBuilder() {
    return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder();
  }

  /**
   * Creates a new TaskStorageConstraintDto RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new TaskStorageConstraintDto RecordBuilder
   */
  public static com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder newBuilder(com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder other) {
    if (other == null) {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder();
    } else {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder(other);
    }
  }

  /**
   * Creates a new TaskStorageConstraintDto RecordBuilder by copying an existing TaskStorageConstraintDto instance.
   * @param other The existing instance to copy.
   * @return A new TaskStorageConstraintDto RecordBuilder
   */
  public static com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder newBuilder(com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto other) {
    if (other == null) {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder();
    } else {
      return new com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder(other);
    }
  }

  /**
   * RecordBuilder for TaskStorageConstraintDto instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<TaskStorageConstraintDto>
    implements org.apache.avro.data.RecordBuilder<TaskStorageConstraintDto> {

    /** Constraint value */
    private double constraintValue;
    /** Date and time of constraint start */
    private java.lang.CharSequence dateTimeStart;
    /** Date and time of constraint end */
    private java.lang.CharSequence dateTimeEnd;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.constraintValue)) {
        this.constraintValue = data().deepCopy(fields()[0].schema(), other.constraintValue);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.dateTimeStart)) {
        this.dateTimeStart = data().deepCopy(fields()[1].schema(), other.dateTimeStart);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.dateTimeEnd)) {
        this.dateTimeEnd = data().deepCopy(fields()[2].schema(), other.dateTimeEnd);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
    }

    /**
     * Creates a Builder by copying an existing TaskStorageConstraintDto instance
     * @param other The existing instance to copy.
     */
    private Builder(com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.constraintValue)) {
        this.constraintValue = data().deepCopy(fields()[0].schema(), other.constraintValue);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.dateTimeStart)) {
        this.dateTimeStart = data().deepCopy(fields()[1].schema(), other.dateTimeStart);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dateTimeEnd)) {
        this.dateTimeEnd = data().deepCopy(fields()[2].schema(), other.dateTimeEnd);
        fieldSetFlags()[2] = true;
      }
    }

    /**
      * Gets the value of the 'constraintValue' field.
      * Constraint value
      * @return The value.
      */
    public double getConstraintValue() {
      return constraintValue;
    }


    /**
      * Sets the value of the 'constraintValue' field.
      * Constraint value
      * @param value The value of 'constraintValue'.
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder setConstraintValue(double value) {
      validate(fields()[0], value);
      this.constraintValue = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'constraintValue' field has been set.
      * Constraint value
      * @return True if the 'constraintValue' field has been set, false otherwise.
      */
    public boolean hasConstraintValue() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'constraintValue' field.
      * Constraint value
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder clearConstraintValue() {
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateTimeStart' field.
      * Date and time of constraint start
      * @return The value.
      */
    public java.lang.CharSequence getDateTimeStart() {
      return dateTimeStart;
    }


    /**
      * Sets the value of the 'dateTimeStart' field.
      * Date and time of constraint start
      * @param value The value of 'dateTimeStart'.
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder setDateTimeStart(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.dateTimeStart = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'dateTimeStart' field has been set.
      * Date and time of constraint start
      * @return True if the 'dateTimeStart' field has been set, false otherwise.
      */
    public boolean hasDateTimeStart() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'dateTimeStart' field.
      * Date and time of constraint start
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder clearDateTimeStart() {
      dateTimeStart = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'dateTimeEnd' field.
      * Date and time of constraint end
      * @return The value.
      */
    public java.lang.CharSequence getDateTimeEnd() {
      return dateTimeEnd;
    }


    /**
      * Sets the value of the 'dateTimeEnd' field.
      * Date and time of constraint end
      * @param value The value of 'dateTimeEnd'.
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder setDateTimeEnd(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.dateTimeEnd = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'dateTimeEnd' field has been set.
      * Date and time of constraint end
      * @return True if the 'dateTimeEnd' field has been set, false otherwise.
      */
    public boolean hasDateTimeEnd() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'dateTimeEnd' field.
      * Date and time of constraint end
      * @return This builder.
      */
    public com.github.kacperpotapczyk.pvoptimizer.avro.backend.calculation.task.TaskStorageConstraintDto.Builder clearDateTimeEnd() {
      dateTimeEnd = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public TaskStorageConstraintDto build() {
      try {
        TaskStorageConstraintDto record = new TaskStorageConstraintDto();
        record.constraintValue = fieldSetFlags()[0] ? this.constraintValue : (java.lang.Double) defaultValue(fields()[0]);
        record.dateTimeStart = fieldSetFlags()[1] ? this.dateTimeStart : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.dateTimeEnd = fieldSetFlags()[2] ? this.dateTimeEnd : (java.lang.CharSequence) defaultValue(fields()[2]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<TaskStorageConstraintDto>
    WRITER$ = (org.apache.avro.io.DatumWriter<TaskStorageConstraintDto>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<TaskStorageConstraintDto>
    READER$ = (org.apache.avro.io.DatumReader<TaskStorageConstraintDto>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeDouble(this.constraintValue);

    out.writeString(this.dateTimeStart);

    out.writeString(this.dateTimeEnd);

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.constraintValue = in.readDouble();

      this.dateTimeStart = in.readString(this.dateTimeStart instanceof Utf8 ? (Utf8)this.dateTimeStart : null);

      this.dateTimeEnd = in.readString(this.dateTimeEnd instanceof Utf8 ? (Utf8)this.dateTimeEnd : null);

    } else {
      for (int i = 0; i < 3; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.constraintValue = in.readDouble();
          break;

        case 1:
          this.dateTimeStart = in.readString(this.dateTimeStart instanceof Utf8 ? (Utf8)this.dateTimeStart : null);
          break;

        case 2:
          this.dateTimeEnd = in.readString(this.dateTimeEnd instanceof Utf8 ? (Utf8)this.dateTimeEnd : null);
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










